apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: matheusmenecucci/frontend-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: LC_ALL
              value: pt_BR.UTF-8
            - name: LANG
              value: pt_BR.UTF-8
            - name: LANGUAGE
              value: pt_BR.UTF-8
          resources:
            requests:
              memory: "1Gi"
              cpu: 1
            limits:
              memory: "2Gi"
              cpu: 2
