apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
    # a mesma porta que voce expoe no dockerfile é a porta de serviço
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: frontend
