services:
  db:
    image: mysql:8.0
    restart: always # garante que o container reinicie automaticamente se parar.
    environment: 
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: calculadora_db
    volumes:
      - db_data:/var/lib/mysql #conexao entre o volume(db_data) fora do conteiner com o caminho dentro do conteiner(/var/lib/mysql)
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # usando o script para criar a tb
    networks: #definindo a rede de acesso
      - minha-rede

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_HOST: db
      DB_NAME: calculadora_db
    networks:
      - minha-rede

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - minha-rede

networks: #definindo a rede compartilhada
  minha-rede:

volumes: #volume externo que armazena os dados de forma persistente(espaco reservado do SO host)
  db_data:

