version: "3.3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: calculadora_db
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # descomente se usar script inicial
    ports:
      - "3307:3306"
    networks:
      - minha-rede

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: 123456789
      DB_HOST: db
      DB_NAME: calculadora_db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - minha-rede

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - minha-rede

networks:
  minha-rede:

volumes:
  db_data:

