apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    run: backend-service
spec:
  ports:
    - port: 8081          # Porta interna do contêiner
      targetPort: 8081     # Porta que o serviço irá expor no contêiner
      nodePort: 30080      # Porta externa que será exposta no nó (pode ser alterada)
      protocol: TCP
  type: NodePort
  selector:
    app: backend
