apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    run: backend
spec:
  ports:
    - port: 8000          # Porta interna do contêiner
      targetPort: 8000     # Porta que o serviço irá expor no contêiner
      nodePort: 30080      # Porta externa que será exposta no nó
      protocol: TCP
  type: NodePort
  selector:
    app: backend
