apiVersion: v1
kind: Service
metadata:
  name: backend-db-service
  labels:
    run: backend-db-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: backend-db
